name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        working-directory: ./
        run: |
          
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/api

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          TAG="${{ github.event.number }}-${{ github.sha }}"
          docker push ${{ secrets.DOCKER_USERNAME }}/api:${TAG}
